#!/bin/sh
#
# Bootstrap a new macOS machine, installing dotfiles, software and configuring
# macOS defaults.

DOTFILES="${HOME}/.dotfiles"

assert_macos() {
  if [ "$(uname -s)" != "Darwin" ]; then
    echo "FATAL: macOS not detected, aborting bootstrap"
    exit 1
  fi
}

link_files() {
  source="${DOTFILES}/${1}"
  dest="${2}"

  if [ -e "${dest}" ] && [ ! -h "${dest}" ]; then
    echo " WARN: symlink failed, \"${dest}\" exists and is not a symlink"
  elif [ -h "${dest}" ] && [ "$(readlink "${dest}")" != "${source}" ]; then
    echo " WARN: symlink failed, \"${dest}\" is linked to another path"
  elif [ ! -e "${dest}" ]; then
    echo " INFO: symlink \"${source}\" to \"${dest}\""
    ln -s "${source}" "${dest}"
  fi
}

sync_dotfiles() {
  echo " INFO: syncing dotfiles"
  rsync \
    --exclude ".DS_Store" \
    --exclude ".git/" \
    --exclude ".github/" \
    --exclude "node_modules/" \
    --archive \
    --human-readable \
    --no-perms \
    . "${DOTFILES}";

  link_files ".editorconfig" "${HOME}/.editorconfig"
  link_files ".gitignore" "${HOME}/.gitignore"
  link_files "git/.gitconfig" "${HOME}/.gitconfig"
  link_files "zsh/.zshrc" "${HOME}/.zshrc"

  mkdir -p "${HOME}/.config"
  link_files "zsh/starship.toml" "${HOME}/.config/starship.toml"
  link_files "vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
}

assert_macos
sync_dotfiles
source homebrew/install
source nodejs/install

if [ -z "${NO_MACOS}" ]; then
  source macos/settings
fi

exit 0
