#!/bin/sh
#
# Install the dotfiles, software and configurations.

DOTFILES="${HOME}/.config/dotfiles"

is_macos() {
  [ "$(uname -s)" = "Darwin" ];
}

link_files() {
  source="${DOTFILES}/${1}"
  dest="${2}"

  if [ -e "${dest}" ] && [ ! -h "${dest}" ]; then
    echo " WARN: symlink failed, \"${dest}\" exists and is not a symlink"
  elif [ -h "${dest}" ] && [ "$(readlink "${dest}")" != "${source}" ]; then
    echo " WARN: symlink failed, \"${dest}\" is linked to another path"
  elif [ ! -e "${dest}" ]; then
    echo " INFO: symlink \"${source}\" to \"${dest}\""
    ln -s "${source}" "${dest}"
  fi
}

sync_dotfiles() {
  echo " INFO: syncing dotfiles"
  mkdir -p "${DOTFILES}"
  rsync \
    --exclude ".DS_Store" \
    --exclude ".git/" \
    --exclude ".github/" \
    --exclude "node_modules/" \
    --archive \
    --human-readable \
    --no-perms \
    . "${DOTFILES}";

  link_files ".editorconfig" "${HOME}/.editorconfig"
  link_files ".gitignore" "${HOME}/.gitignore"
  link_files "git/.gitconfig" "${HOME}/.gitconfig"
  link_files "zsh/.zshrc" "${HOME}/.zshrc"

  mkdir -p "${HOME}/.config/ghostty"
  link_files "ghostty/config" "${HOME}/.config/ghostty/config"
  link_files "zsh/starship.toml" "${HOME}/.config/starship.toml"

  if is_macos; then
    link_files "vscode/settings.json" "${HOME}/Library/Application Support/Code/User/settings.json"
  else
    mkdir -p "${HOME}/.config/Code/User"
    link_files "vscode/settings.json" "${HOME}/.config/Code/User/settings.json"
  fi
}

sync_dotfiles
./homebrew/install
./nodejs/install

if [ "$(uname -s)" = "Darwin" ] && [ -z "${NO_MACOS}" ]; then
  ./macos/settings
fi

exit 0
