[tools]
node = { version = 'lts', postinstall = 'npm install -g tsx typescript typescript-language-server' }
rust = { version = 'latest', components = 'clippy,rust-analyzer,rust-docs,rustfmt' }
go = { version = 'latest', postinstall = 'go install golang.org/x/tools/gopls@latest' }
