[tools]
node = { version = 'lts', postinstall = 'npm install -g tsx typescript typescript-language-server' }
rust = { version = 'latest', profile = 'default', components = 'rust-analyzer' }
go = { version = 'latest', postinstall = 'go install golang.org/x/tools/gopls@latest' }
