#!/bin/sh
#
# Install mise.

install_mise() {
  echo " INFO: installing mise tools and runtimes"
  . "${DOTFILES}/homebrew/path"
  mise --cd "${HOME}" --quiet install | sed -u 's/^/    [mise] /'
}

install_mise
