#!/bin/sh
#
# Configure the keyboard.

configure() {
  echo " INFO: configure the keyboard"

  # Disable add period with double-space.
  defaults write -globalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
}

configure
