#!/bin/sh

configure() {
  echo ' INFO: configure the Keyboard System Settings'

  # Disable add period with double-space.
  defaults write -globalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
}

configure
