#!/bin/sh

configure() {
  echo ' INFO: configure the Menu Bar System Settings'

  # Display the time with seconds.
  defaults write com.apple.menuextra.clock ShowSeconds -bool true

  # Hide Spotlight.
  defaults -currentHost write com.apple.Spotlight MenuItemHidden -int 1
}

configure
