#!/usr/bin/env bash
#
# Configure macOS defaults, based on Mathias Bynens' dotfiles.
# https://github.com/mathiasbynens/dotfiles/blob/main/.macos


################################################################################
# Desktop & Dock
################################################################################

# Set the icon tile size
defaults write com.apple.dock tilesize -int 48

# Enable icon magnification
defaults write com.apple.dock magnification -bool true
defaults write com.apple.dock largesize -int 64

# Position on screen
defaults write com.apple.dock orientation -string bottom

# Minimise window using Genie Effect
defaults write com.apple.dock mineffect -string genie

# Disable double-click a window's title bar to
defaults write com.apple.dock kbehavior -string none

# Don't minimize windows into application icon
defaults write com.apple.dock minimize-to-application -bool false

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Show indicators for open applications
defaults write com.apple.dock show-process-indicators -bool true

# Don't show suggested and recent apps in Dock
defaults write com.apple.dock show-recents -bool false

# Always prefer tabs when opening documents
defaults write com.apple.dock windowtabbing -string always

# Wipe all (default) app icons from the Dock
# This is only really useful when setting up a new Mac, or if you don’t use
# the Dock to launch apps.
defaults write com.apple.dock persistent-apps -array


################################################################################
# Finder
################################################################################

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Don't show warning before changing an extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Remove items from the Bin after 30 days
defaults write com.apple.finder FXRemoveOldTrashItems -bool true

# Keep folders on top when sorting by name
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# When performing a search, search the current folder
defaults write com.apple.finder FXDefaultSearchScope -string SCcf

# Allow quitting via ⌘ + Q
defaults write com.apple.finder QuitMenuItem -bool true

# Use list view
defaults write com.apple.finder FXPreferredViewStyle -string Nlsv

# Show status bar
defaults write com.apple.finder ShowStatusBar -bool true

# Hide all icons from the Desktop
defaults write com.apple.finder CreateDesktop -bool false

# Don't show icons on the desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool false
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true


################################################################################
# Menu Bar
################################################################################

# Display time with seconds
defaults write com.apple.menuextra.clock ShowSeconds -bool true

# Show battery percentage
defaults -currentHost write com.apple.controlcenter BatteryShowPercentage -bool true

echo "Done. Note that some of these changes require a logout/restart to take effect."
