#!/bin/sh
#
# Install Homebrew and software with Homebrew.

install_homebrew() {
  if test ! "$(which brew)"; then
    echo ' INFO: installing Homebrew'
    curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh \
      | NONINTERACTIVE=1 /bin/bash \
      | sed -u 's/^/    [homebrew] /'
  fi
}

install_software() {
  echo ' INFO: installing software with Homebrew Bundle'
  local brewfile="${DOTFILES}/homebrew/Brewfile"
  if [ -n "${DOTFILES_BREWFILE}" ]; then
    brewfile="${DOTFILES_BREWFILE}"
    echo "    [homebrew] using custom Brewfile ${brewfile}"
  fi

  . "${DOTFILES}/homebrew/path"
  brew bundle --file="${brewfile}" --quiet | sed -u 's/^/    [homebrew] /'
}

configure_autoupdate() {
  . "${DOTFILES}/macos/is-macos"
  if is_macos; then
    echo ' INFO: configuring Homebrew autoupdate'
    . "${DOTFILES}/homebrew/path"
    brew tap domt4/autoupdate

    mkdir -p "${HOME}/Library/LaunchAgents"
    brew autoupdate delete | sed -u 's/^/    [homebrew] /'
    brew autoupdate start 604800 --cleanup --upgrade # every 7 days (168 hours).
}

install_homebrew
install_software
configure_autoupdate
