#!/bin/sh
#
# Set the Homebrew path, allowing it to be used by other install scripts.

if [ "$(uname -s)" = 'Darwin' ]; then
  export PATH="/opt/homebrew/bin:$PATH"
else
  export PATH="/home/linuxbrew/.linuxbrew/bin:$PATH"
fi
