#!/bin/sh
#
# Install global Python packages.

install_python_packages() {
  echo " INFO: installing global Python packages"
  pipx install --quiet \
    virtualenv \
    | sed -u 's/^/       /'
}

install_python_packages
