#!/bin/sh
#
# Install Node.js version manager and global Node.js packages.

install_nvm() {
  echo " INFO: installing Node.js version manager"
  export NVM_DIR="${HOME}/.nvm"
  curl -fsSL https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh \
    | PROFILE=/dev/null /bin/bash \
    | sed -u 's/^/    [node.js] /'

  . "${NVM_DIR}/nvm.sh" # Load nvm so it can be used in the install scripts.
  nvm install node
}

install_npm_packages() {
  echo " INFO: installing global Node.js packages"
  npm install --silent --global \
    npm-check-updates \
    tsx \
    typescript \
    wscat
}

install_nvm
install_npm_packages
