#!/bin/sh

install_oh_my_zsh() {
  if [ ! -d "${ZSH}" ]; then
    echo " INFO: installing Oh My Zsh"
    sh -c "$(curl -fsSL https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  fi
}

configure_font() {
  /usr/libexec/PlistBuddy -c \
    'Set :"New Bookmarks":0:"Normal Font" "MesloLGS-NF-Regular 13"' \
    ~/Library/Preferences/com.googlecode.iterm2.plist
}

install_oh_my_zsh
configure_font
