name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@e801b541a7a5bc4d18b82cf822cd498265748002 # v8.1.9
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@e801b541a7a5bc4d18b82cf822cd498265748002 # v8.1.9
    needs:
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
