name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@353e69314e05e5b4117892956a566a70142721fc # v4.2.42
    needs:
      - lint-commit-messages
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
