name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@a54897659db3effb4214e5014ea3486901728203 # v4.2.12
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@a54897659db3effb4214e5014ea3486901728203 # v4.2.12
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@a54897659db3effb4214e5014ea3486901728203 # v4.2.12
    needs:
      - lint-commit-messages
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
