name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@83b254fde3a73f1835299994d551de7d3c23dff2 # v8.1.13
    needs:
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
