name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint-commit-messages:
    uses: vidavidorra/.github/.github/workflows/lint-commit-messages.yml@ce37a41ca867b1a678edb2d4300abdd004e603c4 # v5.0.21
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@ce37a41ca867b1a678edb2d4300abdd004e603c4 # v5.0.21
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@ce37a41ca867b1a678edb2d4300abdd004e603c4 # v5.0.21
    needs:
      - lint-commit-messages
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
