name: CI/CD
on:
  push:
    branches:
      - main
      - beta
      - renovate/**
  pull_request: null
jobs:
  lint:
    uses: vidavidorra/.github/.github/workflows/node-lint.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
  release:
    uses: vidavidorra/.github/.github/workflows/release.yml@2694afc21ede4760dfc7a13061caa14fa247312f # v8.1.12
    needs:
      - lint
    secrets:
      privateKey: ${{ secrets.RELEASE_PRIVATE_KEY }}
